#ifndef __MACRO_CONF__
#define __MACRO_CONF__

// #define CONFIG_ITRACE
// #define CONFIG_FTRACE
#define CONFIG_DIFFTEST
#define CONFIG_MTRACE

#define CONFIG_ISA64 1
#define CONFIG_MSIZE 0x8000000
#define CONFIG_MBASE 0x80000000

#endif